### ISSUE TITLE
No menu show in admin

### ISSUE THREAD

**Issue by pushpendrabkn** [yireo/Yireo_EmailOverride#16]
Hi,
I have installed this plugin through magento connect but it's not showing in admin side. I have cleared my cache and refresh index also. but still it's not showing. 
I am using magenot 1.9

Thanks in advance.

**Comment by jissereitsma** [comment]
What kind of admin menu are you expecting? Did you make sure to read our online instructions: https://www.yireo.com/software/magento-extensions/email-override
