### ISSUE TITLE
Override doesn't work if theme name is not "default"

### ISSUE THREAD

**Issue by bluec** [yireo/Yireo_EmailOverride#25]
If the store theme uses a different name than "default" then this extension won't find the override template files. 

For example, if your package is "mypackage" and the theme is "mytheme" then it will only look for override files in frontend/mypackage/default/locale and not frontend/mypackage/mytheme/locale

This is because the getLocalePaths method in Helper/Data.php is hard coded to use 'default':

`Mage::getBaseDir('design') . DS . 'frontend' . DS . $design['package'] . DS . 'default' . DS . 'locale'`

Should be

`Mage::getBaseDir('design') . DS . 'frontend' . DS . $design['package'] . DS . $design['theme'] . DS . 'locale'`

Or, arguably it should first use $design['theme'] and then fallback to default:

```
        // Default paths
        $paths[] = Mage::getBaseDir('design') . DS . 'frontend' . DS . $design['package'] . DS . $design['theme'] . DS . 'locale';
        $paths[] = Mage::getBaseDir('design') . DS . 'frontend' . DS . $design['package'] . DS . 'default' . DS . 'locale';
        $paths[] = Mage::getBaseDir('design') . DS . 'frontend' . DS . 'default' . DS . 'default' . DS . 'locale';
        $paths[] = Mage::getBaseDir('design') . DS . 'frontend' . DS . 'base' . DS . 'default' . DS . 'locale';
        $paths[] = Mage::getBaseDir('locale');
```

**Comment by jissereitsma** [comment]
Fixed: https://github.com/yireo/Yireo_EmailOverride/commit/d47951517950194091c01c0691dbf368e55ab930
