### ISSUE TITLE
warning on fishpig wordpress compatibility

### ISSUE THREAD

**Issue by MatthewReed** [yireo/Yireo_EmailOverride#34]
After updating your module to the latest version I catch the following warning:

Warning: include(Fishpig/Wordpress/Model/Translate.php): failed to open stream: No such file or directory  in /var/www/xxx.com/htdocs/lib/Varien/Autoload.php on line 94

#0 /var/www/xxx.com/htdocs/lib/Varien/Autoload.php(94): mageCoreErrorHandler(2, 'include(Fishpig...', '/var/www/xxx...', 94, Array)
#1 /var/www/xxx.com/htdocs/lib/Varien/Autoload.php(94): Varien_Autoload::autoload()
#2 [internal function]: Varien_Autoload->autoload('Fishpig_Wordpre...')
#3 [internal function]: spl_autoload_call('Fishpig_Wordpre...')
#4 /var/www/xxx.com/htdocs/app/code/community/Yireo/EmailOverride/Model/Translate/Compatibility.php(11): class_exists('Fishpig_Wordpre...')
#5 /var/www/xxx.com/htdocs/lib/Varien/Autoload.php(94): include('/var/www/xxx...')
#6 [internal function]: Varien_Autoload->autoload('Yireo_EmailOver...')
#7 /var/www/xxx.com/htdocs/app/code/community/Yireo/EmailOverride/Model/Translate.php(15): spl_autoload_call('Yireo_EmailOver...')
#8 /var/www/xxx.com/htdocs/lib/Varien/Autoload.php(94): include('/var/www/xxx...')
#9 [internal function]: Varien_Autoload->autoload('Yireo_EmailOver...')
#10 [internal function]: spl_autoload_call('Yireo_EmailOver...')
#11 /var/www/xxx.com/htdocs/app/code/core/Mage/Core/Model/Config.php(1355): class_exists('Yireo_EmailOver...')
#12 /var/www/xxx.com/htdocs/app/Mage.php(471): Mage_Core_Model_Config->getModelInstance('core/translate', Array)
#13 /var/www/xxx.com/htdocs/app/Mage.php(485): Mage::getModel('core/translate', Array)
#14 /var/www/xxx.com/htdocs/app/code/core/Mage/Core/Model/App.php(1067): Mage::getSingleton('core/translate')
#15 /var/www/xxx.com/htdocs/app/code/core/Mage/Core/Model/App/Area.php(146): Mage_Core_Model_App->getTranslator()
#16 /var/www/xxx.com/htdocs/app/code/core/Mage/Core/Model/App/Area.php(121): Mage_Core_Model_App_Area->_initTranslate()
#17 /var/www/xxx.com/htdocs/app/code/core/Mage/Core/Model/App/Area.php(93): Mage_Core_Model_App_Area->_loadPart('translate')
#18 /var/www/xxx.com/htdocs/app/code/core/Mage/Core/Model/App.php(789): Mage_Core_Model_App_Area->load()
#19 /var/www/xxx.com/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(512): Mage_Core_Model_App->loadArea('frontend')
#20 /var/www/xxx.com/htdocs/app/code/core/Mage/Core/Controller/Front/Action.php(69): Mage_Core_Controller_Varien_Action->preDispatch()
#21 /var/www/xxx.com/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(407): Mage_Core_Controller_Front_Action->preDispatch()
#22 /var/www/xxx.com/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#23 /var/www/xxx.com/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#24 /var/www/xxx.com/htdocs/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#25 /var/www/xxx.com/htdocs/app/Mage.php(692): Mage_Core_Model_App->run(Array)
#26 /var/www/xxx.com/htdocs/index.php(83): Mage::run('', 'store')
#27 {main}

**Comment by jissereitsma** [comment]
This is fixed by reversing the check for the module and the check for the class. Please note that this warning should not occur in production environments, but is meant for developers to either explain themselves or ignore. https://github.com/yireo/Yireo_EmailOverride/blob/master/source/app/code/community/Yireo/EmailOverride/Model/Email/Template/Compatibility.php

**Comment by infabo** [comment]
Hm, Varien Autoloader.

One could get around this by instead of

`-if (class_exists('Fishpig_Wordpress_Model_Translate')`

use 

`-if (class_exists('Fishpig_Wordpress_Model_Translate', false)`

so Varien Autoloader does not kick in.

**Comment by jissereitsma** [comment]
Please see the commits - it's already fixed. Unfortunately, passing the `false` flag to `class_exists` would cause the check to always fail, because autoloading is the trick that this check depends on.

**Comment by infabo** [comment]
@jissereitsma You're right, without beeing "coincidentally" loaded before the check, the class_exists would always fail. I saw the commit, +1 from me. Was some microoptimization that went wrong (class_exists should be less consuming than "isModuleEnabled"). :/

**Comment by jissereitsma** [comment]
No problem. It made me think about whether there was a better option to deal with this, but there isn't. With Magento 2, mechanisms like this are not needed. If we all upgrade to Magento 2, it would solve this :)

**Comment by infabo** [comment]
If only everything could be so easy ;)
