### ISSUE TITLE
Multiple Modules not working anymore

### ISSUE THREAD

**Issue by leonbebb** [yireo/Yireo_EmailOverride#35]
Hello in the Commit "19e5e39" the file: [source/app/code/community/Yireo/EmailOverride/Model/Email/Template/Compatibility.php](https://github.com/yireo/Yireo_EmailOverride/blob/19e5e39a3b04b833ec4556fcfeb9de79c4547356/source/app/code/community/Yireo/EmailOverride/Model/Email/Template/Compatibility.php)
yireo removed the elseif which makes Users which have Multiple Modules running unable to use Yireo_EmailOverride because it is getting called twice.

**Comment by jissereitsma** [comment]
Thanks. It seems indeed that the solution of https://github.com/yireo/Yireo_EmailOverride/commit/19e5e39a3b04b833ec4556fcfeb9de79c4547356#diff-971246dc98a87a8427421192b89c99c2 was less perfect. I've thought about some evil magic like `eval("class $van {};");` but that made me sick. Instead, I think it best to have this change reverted. A new release will be made in 10 minutes or so.

**Comment by jissereitsma** [comment]
https://github.com/yireo/Yireo_EmailOverride/releases/tag/0.2.20
