### ISSUE TITLE
Add infinite theme fallback support for translate.csv files.

### ISSUE THREAD

**Issue by hostep** [yireo/Yireo_EmailOverride#5]
This is perhaps not the correct module to add this functionality, as it has nothing to do with emails.
But since you already do infinite theme fallback for emails and you already rewrite the Translate Model, it kind of makes sense to add it in this module.

So anyway, a colleague of mine added this method to your Yireo_EmailOverride_Model_Translate class, which adds infinite theme fallback support for the translate.csv files:

```
/**
 * Loading current theme translation
 *
 * @return Mage_Core_Model_Translate
 */
protected function _loadThemeTranslation($forceReload = false)
{
    // First add fallback package translate.csv files
    $designPackage = Mage::getSingleton('core/design_package');
    $fallbacks = Mage::getModel('core/design_fallback')->getFallbackScheme($designPackage->getArea(), $designPackage->getPackageName(), $designPackage->getTheme('layout'));
    $fallbackFiles = array();

    foreach ($fallbacks as $fallback)
    {
        if(!isset($fallback['_package']) || !isset($fallback['_theme'])) continue; // first one is empty for some reason
        $fallbackFile = $designPackage->getLocaleFileName('translate.csv', array('_package' => $fallback['_package']));
        $this->_addData($this->_getFileData($fallbackFile), false, $forceReload);
    }

    // Now add current package translate.csv
    $file = Mage::getDesign()->getLocaleFileName('translate.csv');
    $this->_addData($this->_getFileData($file), false, $forceReload);
    return $this;
}
```

(I'm deliberately not creating a pull request as I don't want to take the credit for my colleague's work, and unfortunately he hasn't got a github account (yet).)

**Comment by yireo** [comment]
Thanks for the feedback. Ofcourse, creating a GitHub account is something that can be done in minutes and we strongly encourage it :)

Anyway, I looked at your proposal and it looks great. I have now tested things a bit under Magento 1.8 and Magento 1.9, and because it seems to work fine, I've released a new version containing this addition.

**Comment by hostep** [comment]
Thanks!

Good idea to check backwards compatibility, I didn't think of that :+1:
