### ISSUE TITLE
Compatibility with SMTP Pro Extension by Ashley Schroder

### ISSUE THREAD

**Issue by ihor-sviziev** [yireo/Yireo_EmailOverride#6]
Would be great to have compatibility of this module with [SMTP Pro Extension by Ashley Schroder](https://github.com/aschroder/Magento-SMTP-Pro-Email-Extension). For now we implemented dirty hack https://github.com/ven-com/Yireo_EmailOverride/commit/e6c0e0552e104250b8911eef8c67d95c0dfa08d7

**Comment by yireo** [comment]
This sounds like a great idea. Unfortunately, the only way that Magento allows for making modules like these compatible, is exactly through a hack like this. We will see if we can include this in our documentation though.

**Comment by ihor-sviziev** [comment]
@yireo we may create "base" class , something like this:
```php
<?php

if (Mage::helper('core')->isModuleEnabled(<module name>)) && class_exists(<class name>) {
    class ClassBase extends <class name> {}
} else {
    class ClassBase extends <default class name> {}
}
```

And extends from this class

**Comment by yireo** [comment]
Ok, done, I've now added this workaround specifically for the Aschroder_SMTPPro_Model_Email_Template class in version 0.2.3 of our extension. Will be released in minutes now.

**Comment by ihor-sviziev** [comment]
@yireo thanks!
