### ISSUE TITLE
Blank page when sending order information from admin.

### ISSUE THREAD

**Issue by sanderkwantes** [yireo/Yireo_EmailOverride#7]
Magento system.log and exception.log are not logging info, nginx does:

2015/03/04 16:36:02 [error] 1059#0: *11688 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected '&&' (T_BOOLEAN_AND) in /var/www/XXXXXXXXXXXXX.nl/.modman/Yireo_EmailOverride/source/app/code/community/Yireo/EmailOverride/Model/Email/Template.php on line 12" while reading response header from upstream, client: XX.XX.XX.XXX, server: beta.XXXXXXXXXXXXX.nl, request: "GET /index.php/adminbackend/sales_order/email/order_id/21/key/74ec57e07ab5ea446b4776053e9dc311/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "beta.XXXXXXXXXXX.nl", referrer: "http://beta.XXXXXXXXXXXX.nl/index.php/adminbackend/sales_order/view/order_id/21/key/b5bffd8804e9bae18e431777747d7f5f/"

I work with Magento 1.9.1.0 and i use a custom template based on RWD (not in default or RWD folder). A. Schroder SMTP is used.

**Comment by yireo** [comment]
This looks like a typo. Could you try the new version that is made available minutes ago?

**Comment by sanderkwantes** [comment]
Yes, i can confirm that it works properly now. Thank you!

**Comment by jissereitsma** [comment]
Then the proper way to deal with issues like this, is to close the issue.
